[customizations.installer.kickstart]
contents = """
%post
bootc switch --mutate-in-place --transport registry ghcr.io/ublue-os/my-aurora:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone"
]

disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]

[[customizations.user]]
name = "yasar"
password = "$6$cusUF3OG2QHeBY2O$5m6SVAMzn7MFcoEEJ/0e7Jk7VeICVvrwUIVSNYBGgq.hC09HUESjyrzV6NaYaGxI8WgGSK4L1naQxwzKcaWzB0"
groups = ["wheel"]
